[tool.poetry]
name = "splitdumb-backend"
version = "0.1.0"
description = "SplitDumb backend API"
authors = ["SplitDumb Team"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 100
